# EV0X System - Default Configuration

system:
  name: "ev0x"
  version: "1.0.0"
  log_level: "info"
  data_dir: "./data"

models:
  # Default settings for model configuration
  default_provider: "openai"
  default_temperature: 0.7
  default_max_tokens: 2048
  available_models:
    - name: "gpt-4"
      provider: "openai"
      weight: 1.0
      capabilities:
        - "reasoning"
        - "planning"
        - "creativity"
    - name: "claude-2"
      provider: "anthropic"
      weight: 0.8
      capabilities:
        - "reasoning"
        - "analysis"
        - "factual"
    - name: "llama-2-70b"
      provider: "meta"
      weight: 0.7
      capabilities:
        - "reasoning"
        - "coding"
        - "creative"
  fallback_model: "gpt-3.5-turbo"
  retry_count: 3
  timeout_seconds: 30

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  request_timeout: 60
  rate_limit:
    requests_per_minute: 100
    burst: 20
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]

consensus:
  # Consensus mechanism configuration
  required_agreement: 0.67  # 67% agreement required for consensus
  min_models: 3  # Minimum number of models to participate
  voting_mechanism: "weighted"  # weighted, majority, etc.
  timeout_seconds: 45
  fallback_strategy: "majority_vote"  # What to do if consensus fails
  
evolution:
  # Evolutionary algorithm parameters
  generations: 5
  population_size: 10
  mutation_rate: 0.1
  fitness_evaluation:
    metrics:
      - name: "accuracy"
        weight: 0.6
      - name: "latency"
        weight: 0.2
      - name: "cost"
        weight: 0.2
  selection_mechanism: "tournament"
  tournament_size: 3

bias:
  detector:
    enabled: true
    sensitivity: 0.7
    categories:
      - "political"
      - "racial"
      - "gender"
      - "religious"
  neutralizer:
    enabled: true
    strength: 0.8
    methods: ["reframing", "balancing"]

flare:
  # Default Flare integration settings
  enabled: false
  network: "testnet"
  contract_address: ""
  gas_limit: 3000000
  verification_threshold: 0.8
  observation_submission:
    enabled: false
    frequency: 300  # seconds

tee:
  # Trusted Execution Environment settings
  enabled: false
  provider: "sgx"  # Intel SGX
  attestation_required: true
  encryption:
    algorithm: "AES-256-GCM"
    key_rotation_interval: 86400  # 24 hours in seconds
  memory_protection: true
  secure_storage: true

